---
- name: reload systemd
  become: True
  systemd:
    daemon_reload: yes

- name: restart mailpit
  become: True
  service:
    name: mailpit
    state: restarted

- name: restart nginx
  become: True
  service:
    name: nginx
    state: restarted
